// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YanNote.Models;

namespace YanNote.Migrations
{
    [DbContext(typeof(YanNoteContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("YanNote.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("NoteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TagId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("YanNote.Models.NoteTag", b =>
                {
                    b.Property<int>("NotesId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("NotesId", "TagsId");

                    b.HasIndex(new[] { "TagsId" }, "IX_NoteTag_TagsId");

                    b.ToTable("NoteTag");
                });

            modelBuilder.Entity("YanNote.Models.Rem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NoteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NoteId" }, "IX_Rem_NoteId")
                        .IsUnique();

                    b.ToTable("Rem");
                });

            modelBuilder.Entity("YanNote.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("YanNote.Models.Note", b =>
                {
                    b.HasOne("YanNote.Models.Tag", null)
                        .WithMany("Notes")
                        .HasForeignKey("TagId");
                });

            modelBuilder.Entity("YanNote.Models.NoteTag", b =>
                {
                    b.HasOne("YanNote.Models.Note", "Notes")
                        .WithMany("NoteTags")
                        .HasForeignKey("NotesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YanNote.Models.Tag", "Tags")
                        .WithMany("NoteTags")
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notes");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("YanNote.Models.Rem", b =>
                {
                    b.HasOne("YanNote.Models.Note", "Note")
                        .WithOne("Rem")
                        .HasForeignKey("YanNote.Models.Rem", "NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("YanNote.Models.Note", b =>
                {
                    b.Navigation("NoteTags");

                    b.Navigation("Rem");
                });

            modelBuilder.Entity("YanNote.Models.Tag", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("NoteTags");
                });
#pragma warning restore 612, 618
        }
    }
}
